---
# tasks file for python

- name: Install python3
  apt:
    name: python3
    state: present

- name: Install python mysqldb
  apt: 
    name: python3-mysqldb
    state: present
    
- name: Install python pymysql
  apt: 
    name: python3-pymysql
    state: present

- name: Install pip
  apt: 
    name: python3-pip
    state: present

- name: Install pydev
  apt: 
    name: python3-dev
    state: present